### ISSUE TITLE
Feature Request: "Standing Table" of Contents (always expanded/visible)

### ISSUE THREAD

**Issue by fwolfst** [cosmocode/dokuwiki-template-sprintdoc#22]
Always presenting the users a table of content helps me making them aware of the benefits of structured text and can ease navigation if the context is well-known.

An option to always (according to the rules in the configuration) display the table of content would be awesome. I guess its a non-trivial css-wizardry, though, as the TOC in this template is text-wrap ignoring (it "hovers" the content).

If you think its an pretty low hanging fruit maybe you can give me some pointers where to start looking to make adjustments (unfortunately no real time to work on this, but basic skills are present).

**Comment by ivangretsky** [comment]
Hello, @fwolfst !

Isn't it already implemented as an always visible expandable flag on the top right?

**Comment by splitbrain** [comment]
implemented in a0b1eecca40875d82fbdae15df1664aea12db0c1

**Comment by annda** [comment]
I suppose @fwolfst means something like what we have in the configuration manager, where the TOC is already expanded on page load. 

But I second the decision to close the issue because it would be too obtrusive to show the full TOC by default, as it covers the contents of the page. The sticky solutions seems to be a good compromise IMO.
