### ISSUE TITLE
Logo blurry and aspect ratio ist not kept when resizing the window

### ISSUE THREAD

**Issue by benks-io** [cosmocode/dokuwiki-template-sprintdoc#53]
Having uploaded many version and resolutions of logo.png, logo-square.png, logo-wide.png in wiki:,
still with every version the Logo appears to blurry. Also, the aspect ratio is not kept, when the browsers window size is changed.

**Comment by markgrafd** [comment]
We have the same issue, unfortunately. Is there a recommended resolution for the logos?

**Comment by ivangretsky** [comment]
Seems like the logo of any size is being rescaled to a size lower than needed for appropriate display (height = 50px). If we could turn off this function it would be possible to choose a .png file to look good enough. Or even better make the theme check for an .svg file first.

**Comment by magenbrot** [comment]
![Screenshot_20210209_204033](https://user-images.githubusercontent.com/4865153/107418577-1ecb6c80-6b17-11eb-8fb7-2397dcd97516.png)
I have the same problem with the logo.

**Comment by brueckner** [comment]
One possible and easy improvement could be to change the `image-rendering` mode to `crisp`:

```
image-rendering: -moz-crisp-edges;
image-rendering: -webkit-optimize-contrast;
image-rendering: crisp-edges;
-ms-interpolation-mode: nearest-neighbor;
```

You can just test that using dev-tools and see if it improves things. It doesn't work well in all cases and certainly doesn't fix it completly, but it can be a significant improvement. 

Additionaly, the logo currently has a `width` property, but no `height` property, which leads to unproporional scaling, which is even worse. This can be fixed by setting `height: auto;` on `.logo img`.

---

However, @ivangretsky's suggestion to...
> [...] make the theme check for an .svg file first.

would be the best solution to **actually** fix the blurryness.

**Comment by chrisjrob** [comment]
This problem is also apparent on the [Demo Site](https://demo.sprintdoc.de/). Logo seems to be resized with height 50, but displayed with height 69, with the inevitable consequences. In addition, there is a hover expansion to height 74. Given the importance of the logo, this issue does significantly spoil this template, which otherwise is fantastic.

**Comment by ivangretsky** [comment]
The theme seems to be not so well maintained. So blurry it be,))

**Comment by ivangretsky** [comment]
Great!

**Comment by chrisjrob** [comment]
Absolutely amazing, just needed to Reinstall the template to activate the changes.
Thank you SO much @splitbrain.

**Comment by benks-io** [comment]
@splitbrain Thats looks much better now. :+1:
