### ISSUE TITLE
No MDI-Icon is shown

### ISSUE THREAD

**Issue by KilluSebi** [cosmocode/dokuwiki-template-sprintdoc#56]
I tried to set a custom icon for the sidebar with the following text:
`====== Rules @lock-open-check.svg ======

  * [[home|Home]]`

I just get that:
![image](https://user-images.githubusercontent.com/58842532/87777783-619bbf00-c82a-11ea-81dc-6974b4824874.png)

I used a for the Icon an MDI-Icon

**Comment by annda** [comment]
A possible cause of the problem is that the icons cannot be downloaded because of missing or invalid SSL certificates. It may be due to PHP misconfiguration.

What are your system details (OS, web server, PHP version)?

As a workaround, you can download the Material Design icons, make sure that the files are publicly accessible (no ACL restrictions) and write full ids in the sidebar syntax.
